language: php

php:
    - nightly
    - hhvm
    - 5.5
    - 5.6
    - 7.0
    - 7.1

branches:
    only:
        - master
        - /^\d+\.\d+$/

allow_failures:
    - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate

install: composer update --prefer-dist --no-interaction

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit -d xdebug.max_nesting_level=1000 --debug --coverage-clover build/logs/clover.xml; else phpunit --debug; fi

after_success:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require "satooshi/php-coveralls:^1.0" && travis_retry php vendor/bin/coveralls -v; fi
